repos:
- repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
  rev: v9.13.0
  hooks:
  - id: commitlint
    stages:
    - commit-msg
    additional_dependencies:
    - '@commitlint/config-conventional'
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-json
  - id: check-yaml
- repo: https://github.com/mrtazz/checkmake.git
  rev: 0.2.2
  hooks:
  - id: checkmake
- repo: https://github.com/hadolint/hadolint
  rev: v2.12.0
  hooks:
  - id: hadolint-docker
